apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  storageClassName: csi-hostpath-sc
  